# Generated by Django 6.0.8 on 2026-09-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_absorb_evalrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='evalrun',
            name='provider',
            field=models.CharField(blank=True, default='claude', max_length=32),
        ),
    ]
