# Generated by Django 5.1.15 on 2026-04-18 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('profiles', '0002_tradingprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObserverSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('market_hours_only', models.BooleanField(default=True)),
                ('objective_template', models.TextField(blank=True, default='')),
                ('override_provider', models.CharField(blank=True, default='', max_length=32)),
                ('override_model', models.CharField(blank=True, default='', max_length=100)),
                ('default_includes', models.JSONField(default=list)),
                ('default_watchlist_tickers', models.JSONField(default=list)),
                ('last_fired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periodic_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='django_celery_beat.periodictask')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observer_schedules', to='profiles.tradingprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'enabled'], name='observer_ob_profile_c08fd3_idx')],
            },
        ),
    ]
