# Generated by Django 5.1.15 on 2026-04-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='observerschedule',
            name='mode',
            field=models.CharField(choices=[('full', 'Full payload'), ('diff', 'Diff vs previous capture')], default='full', help_text='diff: feed AI only the delta vs the last ready snapshot.', max_length=8),
        ),
    ]
