# Generated by Django 5.1.15 on 2026-04-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0003_schedule_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='observerschedule',
            name='structured',
            field=models.BooleanField(default=False, help_text='When True, observer runs use messages.parse with the ObservationReport schema instead of streaming text.'),
        ),
    ]
