# Generated by Django 5.1.15 on 2026-04-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0004_schedule_structured'),
    ]

    operations = [
        migrations.AddField(
            model_name='observerschedule',
            name='last_batch_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='observerschedule',
            name='use_batch',
            field=models.BooleanField(default=False, help_text='When True, fires submit a Messages Batch per watchlist ticker instead of streaming. 50% cheaper; not interactive.'),
        ),
    ]
