# Generated by Django 6.0.5 on 2026-05-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0006_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('trigger', 'Trigger'), ('observer_done', 'Observer fired'), ('error', 'Error'), ('cost_limit', 'Cost limit'), ('backup', 'Backup'), ('postmortem', 'Post-mortem')], max_length=16),
        ),
    ]
