# Generated by Django 6.0.5 on 2026-05-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observer", "0006_alter_notification_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="observerschedule",
            name="close_offset_minutes",
            field=models.PositiveIntegerField(
                default=5,
                help_text="Minutes before the actual session close to fire (relative_to_close).",
            ),
        ),
        migrations.AddField(
            model_name="observerschedule",
            name="fire_mode",
            field=models.CharField(
                choices=[("cron", "Cron"), ("relative_to_close", "Relative to close")],
                default="cron",
                max_length=20,
            ),
        ),
    ]
