# Generated by Django 6.0.5 on 2026-05-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0008_observerschedule_close_offset_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('trigger', 'Trigger'), ('observer_done', 'Observer fired'), ('error', 'Error'), ('cost_limit', 'Cost limit'), ('backup', 'Backup'), ('postmortem', 'Post-mortem'), ('briefing', 'Briefing')], max_length=16),
        ),
    ]
