# Generated by Django 6.0.5 on 2026-05-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observer", "0009_alter_notification_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="observerschedule",
            name="consensus",
            field=models.BooleanField(
                default=False,
                help_text="When True (with structured), fan the ObservationReport across every structured-capable provider and record a cross-model agreement signal instead of a single structured report. ~Nx cost; opt-in only.",
            ),
        ),
    ]
