# Generated by Django 6.0.5 on 2026-06-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observer", "0010_observerschedule_consensus"),
    ]

    operations = [
        migrations.AddField(
            model_name="observerschedule",
            name="investigate",
            field=models.BooleanField(
                default=False,
                help_text="When True (plain mode only), the fire runs a bounded tool-using investigation instead of a single observation.",
            ),
        ),
    ]
