# Generated by Django 6.0.5 on 2026-06-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0011_observerschedule_investigate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('trigger', 'Trigger'), ('observer_done', 'Observer fired'), ('error', 'Error'), ('cost_limit', 'Cost limit'), ('backup', 'Backup'), ('postmortem', 'Post-mortem'), ('briefing', 'Briefing'), ('regime', 'Regime')], max_length=16),
        ),
    ]
