# Generated by Django 6.0.6 on 2026-06-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0016_briefingconfig_briefingrun_eventtrigger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprediction',
            name='expected_move_pct',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
