# Generated by Django 6.0.6 on 2026-06-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0018_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('trigger', 'Trigger'), ('observer_done', 'Observer fired'), ('error', 'Error'), ('cost_limit', 'Cost limit'), ('backup', 'Backup'), ('postmortem', 'Post-mortem'), ('briefing', 'Briefing'), ('regime', 'Regime'), ('book', 'Book'), ('desk', 'Desk'), ('cal_drift', 'Calibration drift'), ('contra', 'Consistency conflict')], max_length=16),
        ),
    ]
