# Generated by Django 6.0.6 on 2026-07-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observer", "0019_alter_notification_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("trigger", "Trigger"),
                    ("observer_done", "Observer fired"),
                    ("error", "Error"),
                    ("cost_limit", "Cost limit"),
                    ("backup", "Backup"),
                    ("postmortem", "Post-mortem"),
                    ("briefing", "Briefing"),
                    ("regime", "Regime"),
                    ("book", "Book"),
                    ("desk", "Desk"),
                    ("cal_drift", "Calibration drift"),
                    ("contra", "Consistency conflict"),
                    ("pred_invalid", "Prediction invalidated"),
                ],
                max_length=16,
            ),
        ),
    ]
