# Generated by Django 6.0.8 on 2026-09-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0021_aiprediction_uniq_open_prediction_per_ticker_horizon_profile'),
        ('profiles', '0013_backfill_default_includes'),
        ('snapshots', '0016_alter_snapshotsection_kind'),
        ('threads', '0010_remove_airun_raw_request_summary'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aiprediction',
            name='uniq_open_prediction_per_ticker_horizon_profile',
        ),
        migrations.AddConstraint(
            model_name='aiprediction',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('ticker', 'horizon_days', 'profile', 'provider', 'model'), name='uniq_open_prediction_per_target', nulls_distinct=False),
        ),
    ]
