# Generated by Django 6.0.8 on 2026-09-21 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0022_investigate_default_on_briefing_synthesis'),
        ('observer', '0023_alter_notification_kind_eval_done'),
    ]

    operations = [
    ]
