# Generated by Django 6.0.5 on 2026-05-29 00:28

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='RecallDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('message', 'Message'), ('snapshot', 'Snapshot'), ('thesis', 'Thesis'), ('journal', 'Journal'), ('observation', 'Observation'), ('postmortem', 'PostMortem')], max_length=16)),
                ('object_id', models.IntegerField()),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=64)),
                ('tickers', models.JSONField(default=list)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('search', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('indexed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='recall_emb_hnsw', opclasses=['vector_cosine_ops']), django.contrib.postgres.indexes.GinIndex(fields=['search'], name='recall_search_gin'), models.Index(fields=['-source_created_at'], name='recall_reca_source__30cae2_idx')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'object_id'), name='uniq_recall_doc')],
            },
        ),
    ]
