# Generated by Django 5.1.15 on 2026-04-17 03:03

import apps.secrets.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('schwab', 'Charles Schwab'), ('finnhub', 'Finnhub'), ('marketaux', 'Marketaux')], max_length=32, unique=True)),
                ('token', apps.secrets.fields.EncryptedJSONField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'secrets_apicredential',
            },
        ),
    ]
