# Generated by Django 5.1.15 on 2026-04-17 12:48

import apps.secrets.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('claude', 'Anthropic Claude'), ('openai', 'OpenAI'), ('local', 'Local (OpenAI-compatible)')], max_length=32, unique=True)),
                ('_api_key', apps.secrets.fields.EncryptedJSONField(blank=True, db_column='api_key', null=True)),
                ('base_url', models.CharField(blank=True, default='', max_length=255)),
                ('default_model', models.CharField(blank=True, default='', max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('supports_vision', models.BooleanField(default=True)),
                ('daily_cost_cap_usd', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'secrets_providerconfig',
            },
        ),
    ]
