# Generated by Django 5.1.15 on 2026-04-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_app', '0002_providerconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerconfig',
            name='monthly_cost_cap_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
