# Generated by Django 6.0.5 on 2026-05-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_app', '0003_provider_monthly_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerconfig',
            name='supports_tools',
            field=models.BooleanField(default=True),
        ),
    ]
