# Generated by Django 6.0.5 on 2026-05-31 20:00

import apps.secrets.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_app', '0005_providerconfig_model_discovery'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchwabAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_client_id', apps.secrets.fields.EncryptedJSONField(blank=True, db_column='client_id', null=True)),
                ('_client_secret', apps.secrets.fields.EncryptedJSONField(blank=True, db_column='client_secret', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'secrets_schwabappconfig',
            },
        ),
    ]
