# Generated by Django 6.0.5 on 2026-05-31 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_app', '0006_schwabappconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicredential',
            name='provider',
            field=models.CharField(choices=[('schwab', 'Charles Schwab'), ('finnhub', 'Finnhub'), ('marketaux', 'Marketaux'), ('alpaca', 'Alpaca'), ('tiingo', 'Tiingo'), ('twelvedata', 'Twelve Data'), ('polygon', 'Polygon.io'), ('tradier', 'Tradier'), ('fred', 'FRED (St. Louis Fed)')], max_length=32, unique=True),
        ),
    ]
