# Generated by Django 6.0.5 on 2026-05-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EvalRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual"), ("scheduled", "Scheduled")],
                        default="manual",
                        max_length=12,
                    ),
                ),
                ("label", models.CharField(default="baseline", max_length=64)),
                ("model", models.CharField(db_index=True, max_length=128)),
                ("horizon", models.PositiveIntegerField(blank=True, null=True)),
                ("n", models.PositiveIntegerField(default=0)),
                ("skipped", models.PositiveIntegerField(default=0)),
                ("scored", models.PositiveIntegerField(default=0)),
                ("hit_rate", models.FloatField(blank=True, null=True)),
                ("brier", models.FloatField(blank=True, null=True)),
                ("avg_confidence", models.FloatField(blank=True, null=True)),
                ("calibration_error", models.FloatField(blank=True, null=True)),
                ("calibration", models.JSONField(default=list)),
                ("examples", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["model", "-created_at"], name="aieval_eval_model_27727c_idx"
                    )
                ],
            },
        ),
    ]
