# Generated by Django 5.1.15 on 2026-04-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anthropic_id', models.CharField(max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('filing', 'SEC filing'), ('transcript', 'Earnings transcript'), ('ohlc_csv', 'Historical OHLC CSV'), ('research', 'Research PDF'), ('other', 'Other')], default='other', max_length=16)),
                ('ticker', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('mime', models.CharField(default='application/octet-stream', max_length=64)),
                ('size', models.BigIntegerField(default=0)),
                ('filename', models.CharField(blank=True, default='', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
