line-length = 100
target-version = "py312"
extend-exclude = ["migrations", ".venv", "staticfiles", "frontend"]

[lint]
select = ["E", "F", "I", "B", "UP", "SIM", "DJ", "RUF"]
ignore = ["E501"]

[lint.per-file-ignores]
"**/tests/**" = ["S101"]
"**/settings/*.py" = ["F403", "F405"]

[format]
quote-style = "double"
