# Generated by Django 5.1.15 on 2026-04-18 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_tradingprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('condition', models.JSONField()),
                ('cooldown_seconds', models.PositiveIntegerField(default=1800)),
                ('enabled', models.BooleanField(default=True)),
                ('last_fired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='profiles.tradingprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['enabled', '-last_fired_at'], name='triggers_ev_enabled_3f6a3d_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'name'), name='unique_trigger_name_per_profile')],
            },
        ),
    ]
