# Generated by Django 5.1.15 on 2026-04-18 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0002_snapshotimage'),
        ('threads', '0002_thread_schedule'),
        ('triggers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerFiring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fired_at', models.DateTimeField(auto_now_add=True)),
                ('matched_values', models.JSONField()),
                ('cost_capped', models.BooleanField(default=False)),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trigger_firings', to='snapshots.snapshot')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trigger_firings', to='threads.thread')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firings', to='triggers.eventtrigger')),
            ],
            options={
                'indexes': [models.Index(fields=['trigger', '-fired_at'], name='triggers_tr_trigger_0dabc0_idx'), models.Index(fields=['-fired_at'], name='triggers_tr_fired_a_eb8dc2_idx')],
            },
        ),
    ]
