# Generated by Django 6.0.5 on 2026-05-28 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0006_thesis_guard_enabled'),
        ('triggers', '0003_seed_beat_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtrigger',
            name='source_thesis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guard_triggers', to='thesis.thesis'),
        ),
    ]
