# Generated by Django 6.0.5 on 2026-06-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("triggers", "0004_eventtrigger_source_thesis"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventtrigger",
            name="investigate",
            field=models.BooleanField(
                default=False,
                help_text="When True, a fire runs a bounded tool-using investigation instead of a single observation.",
            ),
        ),
    ]
