# Generated by Django 5.1.15 on 2026-04-17 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WatchlistSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='profiles.watchlist')),
            ],
            options={
                'ordering': ['watchlist_id', 'sort_order'],
                'constraints': [models.UniqueConstraint(fields=('watchlist', 'ticker'), name='uniq_watchlist_ticker')],
            },
        ),
    ]
