# Generated by Django 5.1.15 on 2026-04-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('style', models.TextField(help_text='The trading style text. Prepended as system prompt.')),
                ('default_includes', models.JSONField(default=list)),
                ('default_provider', models.CharField(default='claude', max_length=32)),
                ('default_model', models.CharField(default='claude-sonnet-4-6', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-active', 'name'],
            },
        ),
    ]
