# Generated by Django 5.1.15 on 2026-04-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_tradingprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingprofile',
            name='enable_memory',
            field=models.BooleanField(default=False, help_text='Expose the Memory tool with a per-profile namespace under /data/memory/<profile_id>/.'),
        ),
        migrations.AddField(
            model_name='tradingprofile',
            name='enable_thinking',
            field=models.BooleanField(default=False, help_text='Turn on extended thinking on Claude.'),
        ),
        migrations.AddField(
            model_name='tradingprofile',
            name='enable_tools',
            field=models.BooleanField(default=False, help_text='Expose the default Toolset (get_quote, fetch_ohlc, search_news, get_option_chain, compute_indicator) to Claude.'),
        ),
        migrations.AddField(
            model_name='tradingprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='List of Anthropic Skill ids to attach per run. Empty = none.'),
        ),
        migrations.AddField(
            model_name='tradingprofile',
            name='thinking_budget',
            field=models.PositiveIntegerField(default=8000, help_text='Thinking token budget when enable_thinking=True. Billed as output.'),
        ),
    ]
