# Generated by Django 6.0.5 on 2026-05-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_m10_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('objective_template', models.TextField()),
                ('default_includes', models.JSONField(default=list)),
                ('structured', models.BooleanField(default=False)),
                ('builtin', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-active', 'name'],
            },
        ),
    ]
