# Generated by Django 6.0.5 on 2026-05-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_seed_more_agent_presets'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingprofile',
            name='enable_coach',
            field=models.BooleanField(default=True, help_text='Inject the Decision Coach context (prior theses, diff-vs-last snapshot, per-ticker track record, recall) plus a base observational system prompt. Off = legacy behavior (system prompt is just the style).'),
        ),
    ]
