# Generated by Django 6.0.6 on 2026-06-26 00:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0008_seed_macro_fundamentals_preset"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agentpreset",
            name="default_includes",
        ),
    ]
