# Generated by Django 6.0.6 on 2026-07-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_remove_agentpreset_default_includes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingprofile',
            name='enable_coach',
            field=models.BooleanField(default=True, help_text='Inject the Decision Coach context (prior theses, diff-vs-last snapshot, per-ticker track record, recall) plus a base observational system prompt. Off = the system prompt is just the style.'),
        ),
    ]
