# Generated by Django 6.0.6 on 2026-08-19 19:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0010_alter_tradingprofile_enable_coach"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tradingprofile",
            name="skills",
        ),
    ]
