# Generated by Django 6.0.6 on 2026-08-19 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0011_remove_tradingprofile_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlistsymbol",
            name="watchlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickers",
                to="profiles.watchlist",
            ),
        ),
    ]
