"""Drift gate: docs/toggles.md is what the Features registry renders to.

CLAUDE.md's rule is that `.md` narratives are not gated and must be kept in sync by
hand. This one is the exception: the toggle inventory is the user-facing answer to
"what can I switch, and where", and a hand-maintained copy of 91 rows is stale the
first time a row moves. So the document is generated by `manage.py toggles_doc` and
this test fails when the committed file and the registry disagree.

`docs/` is outside the `web` container's bind mounts (it mounts `./backend` and the
data volume), so the file-comparison test skips there with a stated reason — the same
pattern `test_feature_registry.py` uses for its router.tsx gates — and bites in CI,
which runs pytest from the repo root. `compose.yaml` additionally mounts `./docs`
read-only into `web`, so `make test` exercises it too; the skip is the honest fallback
for any container without that mount.
"""

from __future__ import annotations

import pytest

from apps.core.features import FEATURES, GROUPS
from apps.core.management.commands.toggles_doc import (
    CONNECTIONS,
    DOC_PATH,
    PAGES,
    SCOPE_SINGULAR,
    render,
)

REGENERATE = "docker compose exec -T web uv run python manage.py toggles_doc > docs/toggles.md"

needs_docs = pytest.mark.skipif(
    not DOC_PATH.exists(),
    reason=f"{DOC_PATH} not mounted in this container (CI runs pytest from the repo root)",
)


@needs_docs
def test_committed_doc_matches_the_registry():
    assert DOC_PATH.read_text() == render(), (
        f"{DOC_PATH} no longer matches apps/core/features.py — regenerate it:\n  {REGENERATE}"
    )


def _group_bodies() -> dict[str, list[str]]:
    """The lines under each `## <group label>` heading, keyed by group key."""
    doc = render().splitlines()
    headings = [i for i, line in enumerate(doc) if line.startswith("## ")]
    bodies = {}
    for group in GROUPS:
        start = doc.index(f"## {group.label}")  # ValueError: the section is gone
        end = min([h for h in headings if h > start], default=len(doc))
        bodies[group.key] = doc[start + 1 : end]
    return bodies


def test_every_registry_row_reaches_its_own_group_section():
    """A renderer that silently drops a row would keep the file-comparison gate green.

    Membership in the whole document is too weak a check: a row that also carries an
    environment variable is repeated in the appendix, so its group section could vanish
    entirely and a document-wide search would still find it.
    """
    bodies = _group_bodies()
    missing = sorted(
        f"{f.key} (group {f.group})"
        for f in FEATURES
        if not any(f"**{f.label}**" in line for line in bodies[f.group])
    )
    assert not missing, f"registry row(s) absent from their group's table: {missing}"


def test_every_group_renders_one_table_row_per_registry_row():
    bodies = _group_bodies()
    for group in GROUPS:
        rows = [ln for ln in bodies[group.key] if ln.startswith("| **")]
        expected = sum(1 for f in FEATURES if f.group == group.key)
        assert len(rows) == expected, (
            f"group {group.key!r} renders {len(rows)} table row(s) for {expected} registry row(s)"
        )


def test_no_table_row_renders_an_empty_cell():
    rows = [ln for ln in render().splitlines() if ln.startswith("| **")]
    assert rows, "the document renders no table rows at all"
    empty = [ln for ln in rows if "|  |" in ln]
    assert not empty, f"table row(s) with an empty cell: {empty[:3]}"


def test_every_deep_link_has_a_page_name():
    """A new deep link must be named here, or its rows render with no location."""
    unnamed = sorted({f.deep_link for f in FEATURES if f.deep_link and f.deep_link not in PAGES})
    assert not unnamed, (
        f"deep_link(s) with no page name in toggles_doc.PAGES: {unnamed} — add one, "
        "or the doc cannot say where to change those rows"
    )


def test_every_scope_and_connection_is_nameable():
    scopes = sorted({f.scope for f in FEATURES if f.scope.startswith("per_")} - set(SCOPE_SINGULAR))
    assert not scopes, f"per-object scope(s) with no singular noun: {scopes}"
    conns = sorted(
        {f.requires_connection for f in FEATURES if f.requires_connection} - set(CONNECTIONS)
    )
    assert not conns, f"requires_connection value(s) with no display name: {conns}"


def test_render_is_deterministic():
    assert render() == render()


def test_doc_path_is_anchored_inside_this_checkout():
    """`DOC_PATH` is `parents[5]` of the command module plus `docs/toggles.md`.

    A wrong index resolves to a directory outside the checkout. Nothing raises: the
    path simply does not exist, `needs_docs` skips the file comparison with a
    plausible-sounding reason, and the inventory stops being compared against
    anything. So this asserts the anchor, not the spelling of the last two segments.
    """
    repo_root = DOC_PATH.parents[1]
    anchors = [
        repo_root / "backend" / "apps" / "core" / "features.py",
        repo_root / "backend" / "apps" / "core" / "management" / "commands" / "toggles_doc.py",
    ]
    missing = [str(p) for p in anchors if not p.is_file()]
    assert DOC_PATH.is_absolute()
    assert not missing, (
        f"DOC_PATH is {DOC_PATH}, so the repository root would be {repo_root} — but "
        f"{missing} is not there. Fix the parents[N] index in toggles_doc.py; until "
        "then every gate that reads the committed document skips instead of failing."
    )
