# Generated by Django 6.0.5 on 2026-06-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('as_of_date', models.DateField(unique=True)),
                ('exposures', models.JSONField(default=list)),
                ('concentration', models.JSONField(default=dict)),
                ('clusters', models.JSONField(default=list)),
                ('regime_fit', models.JSONField(default=dict)),
                ('near_invalidation', models.JSONField(default=list)),
                ('narrative', models.TextField(blank=True, default='')),
                ('coverage', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
