# Generated by Django 6.0.5 on 2026-06-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksnapshot',
            name='var_beta',
            field=models.JSONField(default=dict),
        ),
    ]
