# Generated by Django 6.0.6 on 2026-06-24 17:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_booksnapshot_var_beta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booksnapshot",
            name="coverage",
        ),
    ]
