# Generated by Django 6.0.5 on 2026-06-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegimeReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('composite', models.CharField(max_length=20)),
                ('axes', models.JSONField(default=dict)),
                ('drivers', models.JSONField(default=list)),
                ('narrative', models.TextField(blank=True, default='')),
                ('inputs', models.JSONField(default=dict)),
                ('changed_axes', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
