# Generated by Django 6.0.5 on 2026-05-28 08:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0005_seed_agent_presets'),
        ('snapshots', '0004_snapshot_market_state'),
        ('threads', '0004_toolcall'),
    ]

    operations = [
        migrations.CreateModel(
            name='BriefingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('send_at_local', models.TimeField(default=datetime.time(8, 30))),
                ('news_lookback_hours', models.PositiveIntegerField(default=14)),
                ('events_within_days', models.PositiveIntegerField(default=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='profiles.tradingprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BriefingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('assembling', 'Assembling'), ('ready', 'Ready'), ('failed', 'Failed')], default='assembling', max_length=12)),
                ('data', models.JSONField(default=dict)),
                ('scheduled_date', models.DateField(blank=True, null=True, unique=True)),
                ('error', models.TextField(blank=True, default='')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='snapshots.snapshot')),
                ('synthesis_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='threads.message')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
