# Generated by Django 6.0.5 on 2026-05-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ErrorEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("error", "Error"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="error",
                        max_length=16,
                    ),
                ),
                ("source", models.CharField(db_index=True, max_length=128)),
                ("message", models.TextField()),
                ("detail", models.JSONField(blank=True, default=dict)),
                (
                    "fingerprint",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("resolved", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["-created_at"], name="core_errore_created_69292f_idx"),
                    models.Index(
                        fields=["resolved", "-created_at"], name="core_errore_resolve_132bc1_idx"
                    ),
                ],
            },
        ),
    ]
