# Generated by Django 6.0.5 on 2026-05-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_ohlc_days', models.IntegerField(blank=True, null=True)),
                ('retention_chain_days', models.IntegerField(blank=True, null=True)),
                ('retention_notification_days', models.IntegerField(blank=True, null=True)),
                ('retention_error_days', models.IntegerField(blank=True, null=True)),
                ('ai_failover_enabled', models.BooleanField(blank=True, null=True)),
                ('ai_failover_provider', models.CharField(blank=True, max_length=32, null=True)),
                ('observer_response_cache_enabled', models.BooleanField(blank=True, null=True)),
                ('observer_response_cache_ttl_seconds', models.IntegerField(blank=True, null=True)),
                ('aieval_scheduled_enabled', models.BooleanField(blank=True, null=True)),
                ('aieval_scheduled_model', models.CharField(blank=True, max_length=100, null=True)),
                ('aieval_scheduled_horizon', models.IntegerField(blank=True, null=True)),
                ('aieval_scheduled_limit', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'system settings',
                'db_table': 'core_systemsettings',
            },
        ),
    ]
