# Generated by Django 6.0.6 on 2026-06-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='retention_book_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='retention_desk_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='retention_regime_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
