# Generated by Django 6.0.8 on 2026-09-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemsettings_tradingview_tools_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='aieval_scheduled_provider',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
