# Generated by Django 6.0.8 on 2026-09-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_systemsettings_runtime_knobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='book_narrative_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='regime_narrative_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
