# Generated by Django 6.0.8 on 2026-09-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_systemsettings_narrative_toggles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='ai_failover_provider',
            field=models.CharField(blank=True, choices=[('', 'None'), ('claude', 'Anthropic Claude'), ('openai', 'OpenAI'), ('local', 'Local (OpenAI-compatible)')], max_length=32, null=True),
        ),
    ]
