# Generated by Django 6.0.8 on 2026-09-21 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_systemsettings_aieval_scheduled_provider'),
        ('core', '0007_alter_systemsettings_ai_failover_provider'),
    ]

    operations = [
    ]
