# Generated by Django 6.0.5 on 2026-05-30 21:43

from __future__ import annotations

from typing import ClassVar

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar = [
        ("profiles", "0007_tradingprofile_enable_coach"),
        ("thesis", "0006_thesis_guard_enabled"),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=16)),
                (
                    "direction",
                    models.CharField(
                        choices=[("long", "Long"), ("short", "Short")], default="long", max_length=8
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("avg_cost", models.DecimalField(decimal_places=4, max_digits=14)),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "close_price",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
                ),
                (
                    "realized_pnl",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        db_index=True,
                        default="open",
                        max_length=8,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="positions",
                        to="profiles.tradingprofile",
                    ),
                ),
                (
                    "thesis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="positions",
                        to="thesis.thesis",
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-opened_at"], name="portfolio_p_status_dfaf95_idx"
                    ),
                    models.Index(fields=["ticker", "status"], name="portfolio_p_ticker_10dbfb_idx"),
                ],
            },
        ),
    ]
