# Generated by Django 6.0.5 on 2026-05-25 23:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_m10_flags'),
        ('snapshots', '0003_section_payload_tokens'),
        ('threads', '0004_toolcall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ticker', models.CharField(max_length=16)),
                ('direction', models.CharField(choices=[('bullish', 'Bullish'), ('bearish', 'Bearish'), ('neutral', 'Neutral')], max_length=16)),
                ('rationale', models.TextField(blank=True, default='')),
                ('conviction', models.PositiveSmallIntegerField(default=3)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('invalidation_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('horizon_days', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed_win', 'Closed — Win'), ('closed_loss', 'Closed — Loss'), ('closed_scratch', 'Closed — Scratch'), ('invalidated', 'Invalidated')], default='open', max_length=20)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theses', to='profiles.tradingprofile')),
                ('review_thread', models.ForeignKey(blank=True, help_text='Thread where post-mortems will be posted (Phase 2).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_theses', to='threads.thread')),
                ('snapshot', models.ForeignKey(blank=True, help_text='Market state at the time the thesis was opened.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theses', to='snapshots.snapshot')),
                ('thread', models.ForeignKey(blank=True, help_text='Source thread from which this thesis was opened.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theses', to='threads.thread')),
            ],
            options={
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['status', '-opened_at'], name='thesis_thes_status_ff3556_idx')],
            },
        ),
    ]
