# Generated by Django 6.0.5 on 2026-05-26 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0002_alter_thesis_conviction'),
        ('threads', '0004_toolcall'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMortem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon_days', models.IntegerField()),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('done', 'Done'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='scheduled', max_length=16)),
                ('forward_return_pct', models.FloatField(blank=True, null=True)),
                ('verdict', models.CharField(blank=True, choices=[('correct', 'Correct'), ('incorrect', 'Incorrect'), ('mixed', 'Mixed'), ('inconclusive', 'Inconclusive')], default='', max_length=16)),
                ('report', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(blank=True, help_text='The assistant Message posted into the review thread, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='threads.message')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postmortems', to='thesis.thesis')),
            ],
            options={
                'ordering': ['thesis_id', 'horizon_days'],
                'constraints': [models.UniqueConstraint(fields=('thesis', 'horizon_days'), name='uniq_thesis_horizon')],
            },
        ),
    ]
