# Generated by Django 6.0.5 on 2026-05-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("thesis", "0003_postmortem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmortem",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("running", "Running"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                ],
                default="scheduled",
                max_length=16,
            ),
        ),
    ]
