# Generated by Django 6.0.5 on 2026-05-26 01:36

from __future__ import annotations

from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("snapshots", "0003_section_payload_tokens"),
        ("thesis", "0004_alter_postmortem_status"),
        ("threads", "0004_toolcall"),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name="DecisionJournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("acted", "Acted"),
                            ("passed", "Passed"),
                            ("watching", "Watching"),
                            ("hedged", "Hedged"),
                        ],
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_entries",
                        to="snapshots.snapshot",
                    ),
                ),
                (
                    "thesis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_entries",
                        to="thesis.thesis",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to="threads.thread",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["thread", "-created_at"], name="thesis_deci_thread__639e42_idx"
                    )
                ],
            },
        ),
    ]
