# Generated by Django 6.0.5 on 2026-05-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("thesis", "0006_thesis_guard_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="thesis",
            name="invalidation_note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
