# Generated by Django 6.0.6 on 2026-07-05 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0009_lesson'),
        ('threads', '0010_remove_airun_raw_request_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='review_thread',
            field=models.ForeignKey(blank=True, help_text='Thread where post-mortems are posted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_theses', to='threads.thread'),
        ),
    ]
