# Generated by Django 6.0.8 on 2026-09-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0010_alter_thesis_review_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='pinned',
            field=models.BooleanField(default=False, help_text='Reaches the coach regardless of support_n. Hand-written lessons carry no post-mortem evidence, so this is what makes them visible.'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
