# Generated by Django 5.1.15 on 2026-04-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_thread_schedule'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='airun',
            index=models.Index(fields=['created_at'], name='airun_created_idx'),
        ),
        migrations.AddIndex(
            model_name='airun',
            index=models.Index(fields=['provider', 'model', 'created_at'], name='airun_prov_model_idx'),
        ),
    ]
