# Generated by Django 5.1.15 on 2026-04-18 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_airun_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_use_id', models.CharField(max_length=64)),
                ('tool_name', models.CharField(max_length=64)),
                ('tool_input', models.JSONField(default=dict)),
                ('tool_output', models.JSONField(default=dict)),
                ('ok', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True, default='')),
                ('latency_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='threads.message')),
            ],
            options={
                'ordering': ['message_id', 'created_at'],
                'indexes': [models.Index(fields=['message', 'created_at'], name='threads_too_message_46d6c5_idx')],
            },
        ),
    ]
