# Generated by Django 6.0.5 on 2026-05-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("threads", "0005_alter_thread_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="kind",
            field=models.CharField(
                choices=[
                    ("consult", "One-shot consult"),
                    ("chat", "Ongoing chat"),
                    ("observer", "Observer timeline"),
                    ("briefing", "Morning briefing"),
                    ("diff", "Diff"),
                ],
                default="consult",
                max_length=16,
            ),
        ),
    ]
