# Generated by Django 6.0.6 on 2026-06-06 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0007_alter_thread_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airun',
            name='message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_run', to='threads.message'),
        ),
    ]
