# Generated by Django 6.0.6 on 2026-06-24 17:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("threads", "0009_absorb_userfile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="airun",
            name="raw_request_summary",
        ),
    ]
