# Generated by Django 5.1.15 on 2026-04-17 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_tradingprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('includes', models.JSONField(default=list)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('observer', 'Observer'), ('trigger', 'Trigger')], default='manual', max_length=16)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='profiles.tradingprofile')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='SnapshotSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('quotes', 'Quotes'), ('ohlc', 'OHLC'), ('chain', 'Option chain'), ('positions', 'Positions'), ('breadth', 'Market breadth'), ('news', 'News'), ('notes', 'User notes'), ('image', 'Chart image')], max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='snapshots.snapshot')),
            ],
        ),
        migrations.AddIndex(
            model_name='snapshot',
            index=models.Index(fields=['-captured_at'], name='snapshots_s_capture_e18040_idx'),
        ),
        migrations.AddConstraint(
            model_name='snapshotsection',
            constraint=models.UniqueConstraint(fields=('snapshot', 'kind'), name='uniq_snapshot_section'),
        ),
    ]
