# Generated by Django 5.1.15 on 2026-04-17 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('client_capture', 'Client capture'), ('server_render', 'Server render')], max_length=16)),
                ('data', models.BinaryField()),
                ('mime_type', models.CharField(default='image/png', max_length=32)),
                ('caption', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='snapshots.snapshot')),
            ],
        ),
    ]
