# Generated by Django 5.1.15 on 2026-04-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0002_snapshotimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshotsection',
            name='payload_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
