# Generated by Django 6.0.5 on 2026-05-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0003_section_payload_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='market_state',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
