# Generated by Django 6.0.5 on 2026-05-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0004_snapshot_market_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('observer', 'Observer'), ('trigger', 'Trigger'), ('briefing', 'Briefing')], default='manual', max_length=16),
        ),
    ]
