# Generated by Django 6.0.5 on 2026-05-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0005_alter_snapshot_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='manual_positions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
