# Generated by Django 6.0.5 on 2026-05-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0006_snapshot_manual_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='primary_ticker',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
    ]
