# Generated by Django 6.0.5 on 2026-05-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0008_backfill_primary_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='overnight',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='snapshotsection',
            name='kind',
            field=models.CharField(choices=[('quotes', 'Quotes'), ('ohlc', 'OHLC'), ('chain', 'Option chain'), ('positions', 'Positions'), ('breadth', 'Market breadth'), ('news', 'News'), ('notes', 'User notes'), ('image', 'Chart image'), ('overnight', 'Overnight board')], max_length=16),
        ),
    ]
