# Generated by Django 6.0.5 on 2026-05-31 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0009_snapshot_overnight_alter_snapshotsection_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshotsection',
            name='kind',
            field=models.CharField(choices=[('quotes', 'Quotes'), ('ohlc', 'OHLC'), ('chain', 'Option chain'), ('positions', 'Positions'), ('breadth', 'Market breadth'), ('news', 'News'), ('notes', 'User notes'), ('image', 'Chart image'), ('overnight', 'Overnight board'), ('events', 'Upcoming events'), ('fundamentals', 'Company fundamentals')], max_length=16),
        ),
    ]
