# Generated by Django 6.0.5 on 2026-05-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0010_alter_snapshotsection_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshotimage',
            name='file_path',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='snapshotimage',
            name='data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
