# Generated by Django 6.0.5 on 2026-05-31 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0011_snapshotimage_file_path_alter_snapshotimage_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshotsection',
            name='kind',
            field=models.CharField(choices=[('quotes', 'Quotes'), ('ohlc', 'OHLC'), ('chain', 'Option chain'), ('positions', 'Positions'), ('breadth', 'Market breadth'), ('news', 'News'), ('notes', 'User notes'), ('image', 'Chart image'), ('overnight', 'Overnight board'), ('events', 'Upcoming events'), ('fundamentals', 'Company fundamentals'), ('macro', 'Macro indicators'), ('filings', 'SEC filings'), ('treasury', 'Treasury rates')], max_length=16),
        ),
    ]
