# Generated by Django 6.0.5 on 2026-06-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snapshots", "0012_alter_snapshotsection_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="snapshot",
            name="candidate_positions",
            field=models.TextField(blank=True, default=""),
        ),
    ]
