# Generated by Django 6.0.6 on 2026-06-25 23:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("snapshots", "0013_snapshot_candidate_positions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="snapshot",
            name="overnight",
        ),
    ]
