# Generated by Django 5.1.15 on 2026-04-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spy_last', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('qqq_last', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('vix_last', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('sectors', models.JSONField(default=dict)),
                ('breadth', models.JSONField(default=dict)),
                ('as_of', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='OHLCBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=16)),
                ('timeframe', models.CharField(choices=[('1m', '1m'), ('5m', '5m'), ('15m', '15m'), ('1h', '1h'), ('1d', '1d')], max_length=4)),
                ('open', models.DecimalField(decimal_places=4, max_digits=14)),
                ('high', models.DecimalField(decimal_places=4, max_digits=14)),
                ('low', models.DecimalField(decimal_places=4, max_digits=14)),
                ('close', models.DecimalField(decimal_places=4, max_digits=14)),
                ('volume', models.BigIntegerField()),
                ('ts', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', 'timeframe', '-ts'], name='market_ohlc_ticker_3cf408_idx')],
                'constraints': [models.UniqueConstraint(fields=('ticker', 'timeframe', 'ts'), name='uniq_bar')],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=16)),
                ('qty', models.DecimalField(decimal_places=6, max_digits=16)),
                ('avg_cost', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('mkt_value', models.DecimalField(decimal_places=4, max_digits=16, null=True)),
                ('unrealized_pl', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('day_pl', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('as_of', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', '-as_of'], name='market_posi_ticker_7696ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=16)),
                ('last', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('bid', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('ask', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('volume', models.BigIntegerField(null=True)),
                ('high', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('low', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('pct_change', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('ts', models.DateTimeField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', '-ts'], name='market_quot_ticker_33302a_idx')],
            },
        ),
    ]
