# Generated by Django 5.1.15 on 2026-04-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionChainSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=16)),
                ('expiries', models.JSONField(default=list)),
                ('payload', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', '-fetched_at'], name='market_opti_ticker_12d340_idx')],
            },
        ),
    ]
