# Generated by Django 5.1.15 on 2026-04-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_optionchainsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=16)),
                ('external_id', models.CharField(db_index=True, max_length=64)),
                ('ticker', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('headline', models.CharField(max_length=512)),
                ('summary', models.TextField(blank=True, default='')),
                ('url', models.URLField(max_length=1024)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('published_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', '-published_at'], name='market_news_ticker_977a27_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_id'), name='uniq_news_provider_id')],
            },
        ),
    ]
