# Generated by Django 5.2.14 on 2026-05-24 22:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0003_newsitem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MarketContext",
        ),
        migrations.DeleteModel(
            name="Position",
        ),
        migrations.DeleteModel(
            name="Quote",
        ),
    ]
