# Generated by Django 6.0.5 on 2026-05-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0004_delete_marketcontext_delete_position_delete_quote"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("symbol", models.CharField(max_length=16, unique=True)),
                (
                    "market_key",
                    models.CharField(
                        choices=[
                            ("us_equity", "US equities (NYSE/NASDAQ)"),
                            ("us_bond", "US bonds (SIFMA)"),
                            ("cme_futures", "CME futures"),
                            ("cfe_futures", "CFE / VIX futures"),
                            ("crypto", "Crypto (24/7)"),
                            ("lse", "London (LSE)"),
                            ("jpx", "Tokyo (JPX)"),
                        ],
                        max_length=16,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
