# Generated by Django 6.0.5 on 2026-05-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_calendaroverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=16)),
                ('external_id', models.CharField(db_index=True, max_length=80)),
                ('kind', models.CharField(choices=[('earnings', 'earnings'), ('fomc', 'fomc'), ('cpi', 'cpi'), ('nfp', 'nfp'), ('pce', 'pce'), ('gdp', 'gdp')], max_length=16)),
                ('ticker', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('event_time', models.DateTimeField(db_index=True)),
                ('when_hint', models.CharField(blank=True, default='', max_length=8)),
                ('impact', models.CharField(blank=True, default='', max_length=8)),
                ('detail', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', 'event_time'], name='market_mark_ticker_799f60_idx'), models.Index(fields=['kind', 'event_time'], name='market_mark_kind_1b50e1_idx'), models.Index(fields=['event_time'], name='market_mark_event_t_8e7148_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_event_source_id')],
            },
        ),
    ]
