# Generated by Django 6.0.5 on 2026-05-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("market", "0006_marketevent"),
    ]

    operations = [  # noqa: RUF012
        migrations.CreateModel(
            name="CompanyFundamentals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=16)),
                ("sector", models.CharField(blank=True, default="", max_length=64)),
                ("industry", models.CharField(blank=True, default="", max_length=96)),
                ("metrics", models.JSONField(default=dict)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("ticker",), name="uniq_fundamentals_ticker")
                ],
            },
        ),
    ]
