# Generated by Django 6.0.5 on 2026-05-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0007_companyfundamentals"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorporateAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source", models.CharField(max_length=16)),
                ("external_id", models.CharField(db_index=True, max_length=80)),
                (
                    "kind",
                    models.CharField(
                        choices=[("split", "split"), ("dividend", "dividend")], max_length=16
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=16)),
                ("ex_date", models.DateField(db_index=True)),
                (
                    "ratio",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
                ),
                ("detail", models.JSONField(default=dict)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ticker", "ex_date"], name="market_corp_ticker_bb67b7_idx"
                    ),
                    models.Index(fields=["kind", "ex_date"], name="market_corp_kind_bdf152_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "external_id"), name="uniq_corpaction_source_id"
                    )
                ],
            },
        ),
    ]
