# Generated by Django 5.1.15 on 2026-04-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('size_bytes', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual')], max_length=16)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('failed', 'Failed'), ('rotated', 'Rotated'), ('deleted', 'Deleted'), ('missing', 'Missing')], max_length=16)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
