# Generated by Django 6.0.6 on 2026-06-24 17:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("strategy", "0002_regimereading"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warroomrun",
            name="confidence",
        ),
    ]
