# Generated by Django 6.0.5 on 2026-06-01 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeskEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('anomaly_type', models.CharField(db_index=True, max_length=32)),
                ('ticker', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('severity', models.FloatField(default=0.0)),
                ('evidence', models.JSONField(default=dict)),
                ('finding', models.TextField(blank=True, default='')),
                ('suggested_actions', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('new', 'New'), ('acted', 'Acted'), ('dismissed', 'Dismissed')], db_index=True, default='new', max_length=16)),
                ('warroom_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='warroom.warroomrun')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ticker', 'anomaly_type', '-created_at'], name='desk_desken_ticker_ac168d_idx')],
            },
        ),
    ]
