# Generated by Django 6.0.5 on 2026-06-01 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0001_initial'),
        ('threads', '0007_alter_thread_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='deskentry',
            name='investigation_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='threads.thread'),
        ),
    ]
