# Generated by Django 6.0.5 on 2026-06-01 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        ('coverage', '0001_initial'),
        ('thesis', '0007_thesis_invalidation_note'),
        ('threads', '0007_alter_thread_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarRoomRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('subject_kind', models.CharField(max_length=16)),
                ('subject_label', models.CharField(blank=True, default='', max_length=200)),
                ('free_prompt', models.TextField(blank=True, default='')),
                ('params', models.JSONField(default=dict)),
                ('verdict', models.JSONField(default=dict)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('done', 'Done'), ('error', 'Error')], default='done', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('book_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='book.booksnapshot')),
                ('coverage_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='coverage.coveragenote')),
                ('thesis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='thesis.thesis')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warroom_runs', to='threads.thread')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
