# Generated by Django 6.0.5 on 2026-06-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warroomrun',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='done', max_length=16),
        ),
    ]
