# Generated by Django 6.0.5 on 2026-06-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('thesis', '0007_thesis_invalidation_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Representative bullet of the cluster.')),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('tags', models.JSONField(default=dict)),
                ('support_n', models.PositiveIntegerField(default=0, help_text='Number of post-mortems supporting this lesson.')),
                ('muted', models.BooleanField(default=False, help_text='Hidden from the coach when True.')),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence', models.ManyToManyField(blank=True, related_name='lessons', to='thesis.postmortem')),
            ],
            options={
                'ordering': ['-support_n', '-last_seen'],
                'indexes': [models.Index(fields=['muted', '-support_n'], name='lessons_les_muted_44468c_idx')],
            },
        ),
    ]
